fix: prevent error on destroy in `StopEscapePropagationDirective`
Unit test error reported by a user:

```
TypeError: Cannot read properties of undefined (reading 'unsubscribe')
    at StopEscapePropagationDirective.call [as ngOnDestroy] (node_modules/@clr/angular/fesm2020/clr-angular.mjs:2620:27)
    at executeOnDestroys (node_modules/@angular/core/fesm2020/core.mjs:6031:32)
    at cleanUpView (node_modules/@angular/core/fesm2020/core.mjs:5941:9)
    at destroyViewTree (node_modules/@angular/core/fesm2020/core.mjs:5774:17)
```

I am not sure how this is possible. The `ngOnDestroy` method is
apparently sometimes called without `ngOnInit` having been called first.
I think this is just a possible unit testing issue. In any case, it's a
simple fix to conditionally unsubscribe.