fix(modal): provide modal config service in root and export (#1556)
## What is the current behavior?

The following error occurs when using `VmwNgxModalService`:

```
ERROR NullInjectorError: R3InjectorError(Environment Injector)[ClrModalConfigurationService -> ClrModalConfigurationService]:
  NullInjectorError: No provider for ClrModalConfigurationService!
    at NullInjector.get (core.mjs:1635:21)
    at R3Injector.get (core.mjs:3017:27)
    at R3Injector.get (core.mjs:3017:27)
    at ChainedInjector.get (core.mjs:5288:32)
    at lookupTokenUsingModuleInjector (core.mjs:5631:31)
    at getOrCreateInjectable (core.mjs:5677:10)
    at ɵɵdirectiveInject (core.mjs:11586:17)
    at NodeInjectorFactory.ClrModal_Factory [as factory] (clr-angular.mjs:32885:177)
    at getNodeInjectable (core.mjs:5871:38)
    at instantiateAllDirectives (core.mjs:12403:23)
```

Issue Number: CDE-2293

## What is the new behavior?

No error occurs when using `VmwNgxModalService`.

(cherry picked from commit 29eed4caba66d98d870dc565b7f934e887a5d327)