fix(datagrid): propagate cell rendering changes only to owned rows (backport to 16.x) (#1619)
Backport 6c4b36edd86599f4eb38d2b59e31b3e26ee49dfd from #1489. <br> This
change prevents propagation of cell rendering changes to rows owned by
nested datagrids.

CDE-2199
closes #1485

## PR Checklist

- [x] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)
- [N/A] If applicable, have a visual design approval

## PR Type

Bugfix

## What is the current behavior?

If the detail pane of a datagrid contains another datagrid with less
columns than the outer datagrid, closing the detail pane results in the
error: `row.cells.get(...) is undefined`.

Issue Number: #1485, CDE-2199

## What is the new behavior?

No error is thrown, and the correct cells are hidden.

## Does this PR introduce a breaking change?

No.

Co-authored-by: Kevin Buhmann <kbuhmann@vmware.com>